'use strict';
// Only interface copy belongs here; English keys are the fallback catalog.
window.LEGAL_LIBRARY_VI=Object.freeze({
  "Not recorded": "Chưa ghi nhận",
  "Legal Library": "Thư viện pháp lý",
  "Close dialog": "Đóng hộp thoại",
  "Your organization’s knowledge": "Kho tri thức của tổ chức",
  "Queued": "Đang chờ xử lý",
  "Reading file": "Đang đọc tệp",
  "Text extracted": "Đã trích xuất văn bản",
  "Organizing content": "Đang sắp xếp nội dung",
  "Content organized": "Đã sắp xếp nội dung",
  "Preparing passages": "Đang chuẩn bị đoạn trích",
  "Building search": "Đang tạo dữ liệu tìm kiếm",
  "Finishing": "Đang hoàn tất",
  "Passages prepared": "Đã chuẩn bị đoạn trích",
  "Search prepared": "Đã tạo dữ liệu tìm kiếm",
  "Ready": "Sẵn sàng",
  "Needs attention": "Cần kiểm tra",
  "Archived": "Đã lưu trữ",
  "The server is unavailable": "Không thể kết nối với máy chủ",
  "Try again": "Thử lại",
  "Welcome back": "Chào mừng bạn trở lại",
  "Create your account": "Tạo tài khoản",
  "Set up your library": "Thiết lập thư viện",
  "Reset your password": "Đặt lại mật khẩu",
  "Sign in to your organization’s document library.": "Đăng nhập vào thư viện tài liệu của tổ chức.",
  "Your administrator will approve access, unless you have an invitation.": "Quản trị viên sẽ duyệt yêu cầu truy cập, trừ khi bạn đã có mã mời.",
  "Create the first administrator account on this server.": "Tạo tài khoản quản trị viên đầu tiên trên máy chủ này.",
  "Ask your administrator for a recovery code. It is valid for one hour.": "Liên hệ quản trị viên để nhận mã khôi phục. Mã có hiệu lực trong một giờ.",
  "Server setup code": "Mã thiết lập máy chủ",
  "Find this code in Legal Library Server on the host machine. It prevents someone else on the network from claiming your server.": "Xem mã trong ứng dụng máy chủ Thư viện pháp lý trên máy chủ. Mã này ngăn người khác trong mạng chiếm quyền thiết lập máy chủ của bạn.",
  "Your name": "Họ và tên",
  "Username": "Tên đăng nhập",
  "Email (optional)": "Email (không bắt buộc)",
  "Invitation code (optional)": "Mã mời (không bắt buộc)",
  "Recovery code": "Mã khôi phục",
  "New password": "Mật khẩu mới",
  "Password": "Mật khẩu",
  "Use at least 12 characters. A memorable phrase works well.": "Dùng ít nhất 12 ký tự. Bạn có thể dùng một cụm từ dễ nhớ.",
  "Confirm password": "Nhập lại mật khẩu",
  "Create an account": "Tạo tài khoản",
  "Forgot password?": "Quên mật khẩu?",
  "Back to sign in": "Quay lại đăng nhập",
  "Knowledge you can check": "Tri thức có thể kiểm chứng",
  "Find the answer.": "Tìm câu trả lời.",
  "See the source.": "Đối chiếu nguồn.",
  "A shared home for your policies and legal documents, with passages you can verify and references you can keep.": "Nơi lưu trữ chung các quy định và tài liệu pháp lý, với đoạn trích có thể kiểm chứng và nguồn tham khảo có thể lưu lại.",
  "Built for Vietnamese documents. Available to your team.": "Dành cho tài liệu tiếng Việt. Chia sẻ cùng đội ngũ của bạn.",
  "Sign in": "Đăng nhập",
  "Request access": "Yêu cầu truy cập",
  "Create administrator": "Tạo quản trị viên",
  "Reset password": "Đặt lại mật khẩu",
  "Overview": "Tổng quan",
  "Ask your documents": "Hỏi đáp tài liệu",
  "Search": "Tìm kiếm",
  "Documents": "Tài liệu",
  "Collections": "Bộ sưu tập",
  "Saved answers": "Câu trả lời đã lưu",
  "People": "Người dùng",
  "Server settings": "Cài đặt máy chủ",
  "Find it. Verify it. Keep it.": "Tìm kiếm. Kiểm chứng. Lưu giữ.",
  "Help": "Trợ giúp",
  "Loading…": "Đang tải…",
  "Main navigation": "Điều hướng chính",
  "Administrator": "Quản trị viên",
  "Team member": "Thành viên",
  "Sign out": "Đăng xuất",
  "AI-assisted source selection": "Chọn nguồn với sự hỗ trợ của AI",
  "Local search · vision OCR": "Tìm kiếm cục bộ · OCR bằng mô hình thị giác",
  "Local document library": "Thư viện tài liệu cục bộ",
  "Documents {{0}}–{{1}} of {{2}}. Processing updates automatically.": "Tài liệu {{0}}–{{1}} trên tổng số {{2}}. Trạng thái xử lý được cập nhật tự động.",
  "Previous": "Trước",
  "Next": "Tiếp",
  "Your evidence, in one place": "Nguồn tham khảo của bạn, ở cùng một nơi",
  "Good answers start": "Câu trả lời đáng tin cậy",
  "with the right documents.": "bắt đầu từ tài liệu phù hợp.",
  "Search your team’s knowledge and find source passages you can inspect, share and return to.": "Tra cứu tri thức của đội ngũ và tìm các đoạn trích để kiểm tra, chia sẻ và tham khảo lại.",
  "Ask your documents →": "Hỏi đáp tài liệu →",
  "Upload documents": "Tải tài liệu lên",
  "Documents ready to use": "Tài liệu sẵn sàng sử dụng",
  "Collections you can access": "Bộ sưu tập bạn có quyền truy cập",
  "Documents needing attention": "Tài liệu cần kiểm tra",
  "A simple path to your first answer": "Các bước để tìm câu trả lời đầu tiên",
  "01 / COLLECT": "01 / TẬP HỢP",
  "Create a collection": "Tạo bộ sưu tập",
  "Keep a set of policies together. Share it with the people who need it.": "Tập hợp các quy định vào một nơi. Chia sẻ với những người cần sử dụng.",
  "Manage collections →": "Quản lý bộ sưu tập →",
  "02 / UPLOAD": "02 / TẢI LÊN",
  "Add your source documents": "Thêm tài liệu nguồn",
  "Upload PDF or DOCX files. You’ll see when each document is ready.": "Tải tệp PDF hoặc DOCX lên. Bạn sẽ thấy khi từng tài liệu sẵn sàng.",
  "Add documents →": "Thêm tài liệu →",
  "03 / VERIFY": "03 / KIỂM CHỨNG",
  "Ask and inspect the source": "Đặt câu hỏi và kiểm tra nguồn",
  "Choose your scope and date, then open the passage behind each result.": "Chọn phạm vi và ngày áp dụng, rồi mở đoạn trích làm căn cứ cho từng kết quả.",
  "Ask a question →": "Đặt câu hỏi →",
  "Search runs locally. Scanned page images may be sent to the administrator-approved vision OCR provider.": "Tìm kiếm được thực hiện cục bộ. Ảnh trang quét có thể được gửi đến nhà cung cấp OCR thị giác do quản trị viên phê duyệt.",
  "Local search and Tesseract OCR run on this server. Your administrator can separately enable AI-assisted selection or vision OCR.": "Tìm kiếm cục bộ và Tesseract OCR chạy trên máy chủ này. Quản trị viên có thể bật riêng tính năng chọn nguồn bằng AI hoặc OCR bằng mô hình thị giác.",
  "AI-assisted selection is enabled. Your administrator controls which provider processes questions and relevant document passages.": "Đã bật chọn nguồn bằng AI. Quản trị viên quyết định nhà cung cấp xử lý câu hỏi và các đoạn tài liệu liên quan.",
  "Organize documents and choose who can read or contribute.": "Sắp xếp tài liệu và chọn người được đọc hoặc đóng góp.",
  "+ New collection": "+ Bộ sưu tập mới",
  "{{3}} documents · {{4}}": "{{3}} tài liệu · {{4}}",
  "Open": "Mở",
  "Ask": "Hỏi đáp",
  "Personal collection": "Bộ sưu tập cá nhân",
  "Team collection": "Bộ sưu tập của nhóm",
  "Shared collection": "Bộ sưu tập dùng chung",
  "Collection": "Bộ sưu tập",
  "A collection of your team’s documents.": "Bộ sưu tập tài liệu của đội ngũ.",
  "Sharing": "Chia sẻ",
  "Create a home for your documents": "Tạo nơi lưu trữ tài liệu",
  "Start with a collection such as Procurement policies or Internal procedures.": "Bắt đầu bằng một bộ sưu tập như Quy định mua sắm hoặc Quy trình nội bộ.",
  "Create collection": "Tạo bộ sưu tập",
  "All accessible collections": "Tất cả bộ sưu tập được phép truy cập",
  "Choose a collection": "Chọn bộ sưu tập",
  "Find a document across your library, inspect its source and track processing.": "Tìm tài liệu trong thư viện, kiểm tra nguồn và theo dõi quá trình xử lý.",
  "+ Upload documents": "+ Tải tài liệu lên",
  "Apply filters": "Áp dụng bộ lọc",
  "Clear filters": "Xóa bộ lọc",
  "Title or document number": "Tiêu đề hoặc số hiệu văn bản",
  "Show": "Hiển thị",
  "Active documents": "Tài liệu đang sử dụng",
  "Ready to use": "Sẵn sàng sử dụng",
  "Processing": "Đang xử lý",
  "All documents": "Tất cả tài liệu",
  "Document": "Tài liệu",
  "Status": "Trạng thái",
  "Effective date": "Ngày có hiệu lực",
  "Actions": "Thao tác",
  "Not verified": "Chưa xác minh",
  "Retry": "Thử lại",
  "Details": "Chi tiết",
  "No matching documents": "Không có tài liệu phù hợp",
  "Try another collection, title or status. You can also add a document to a collection you contribute to.": "Thử bộ sưu tập, tiêu đề hoặc trạng thái khác. Bạn cũng có thể thêm tài liệu vào bộ sưu tập mà bạn được phép đóng góp.",
  "Could not refresh processing status. Reload to try again.": "Không thể cập nhật trạng thái xử lý. Tải lại trang để thử lại.",
  "Uploading documents": "Đang tải tài liệu lên",
  "Your current batch is being sent to the server.": "Lô tài liệu hiện tại đang được gửi đến máy chủ.",
  "Keep this browser open until uploading finishes. You can browse other pages while processing continues.": "Giữ trình duyệt mở cho đến khi tải lên hoàn tất. Bạn có thể xem các trang khác trong khi máy chủ xử lý.",
  "View documents": "Xem tài liệu",
  "Add documents": "Thêm tài liệu",
  "Choose files, check their names and let the library prepare them.": "Chọn tệp, kiểm tra tên và để thư viện chuẩn bị nội dung.",
  "Choose a collection you can contribute to": "Chọn bộ sưu tập bạn được phép đóng góp",
  "Ask a collection manager for contributor access, or create your own collection.": "Nhờ người quản lý cấp quyền đóng góp hoặc tạo bộ sưu tập của riêng bạn.",
  "Select your documents": "Chọn tài liệu",
  "PDF and DOCX · up to 25 MB per file · up to 50 files per batch": "PDF và DOCX · tối đa 25 MB mỗi tệp · tối đa 50 tệp mỗi lần",
  "Or choose a folder": "Hoặc chọn thư mục",
  "Document details (optional)": "Thông tin tài liệu (không bắt buộc)",
  "Dates apply to this batch. Leave them empty if they have not been verified.": "Các ngày áp dụng cho cả lô tài liệu. Để trống nếu chưa xác minh.",
  "Scanned pages need OCR on the server. Unreadable files remain visible for correction.": "Trang quét cần được nhận dạng OCR trên máy chủ. Tệp không đọc được vẫn hiển thị để bạn khắc phục.",
  "Select documents": "Chọn tài liệu",
  "Select a document folder": "Chọn thư mục tài liệu",
  "Save to collection": "Lưu vào bộ sưu tập",
  "Issued by (optional)": "Cơ quan ban hành (không bắt buộc)",
  "Document type": "Loại văn bản",
  "Policy or internal document": "Quy định hoặc tài liệu nội bộ",
  "Decision": "Quyết định",
  "Circular": "Thông tư",
  "Decree": "Nghị định",
  "Law": "Luật",
  "Effective from": "Có hiệu lực từ",
  "Effective until": "Có hiệu lực đến",
  "Tags": "Nhãn",
  "Document title": "Tiêu đề tài liệu",
  "Uploaded. Processing continues in Documents.": "Đã tải lên. Theo dõi quá trình xử lý trong mục Tài liệu.",
  "Search the library": "Tìm kiếm trong thư viện",
  "Find relevant source passages, then check the wording and context.": "Tìm đoạn trích liên quan, rồi kiểm tra câu chữ và ngữ cảnh.",
  "Look up a policy, phrase, document number or topic.": "Tra cứu quy định, cụm từ, số hiệu văn bản hoặc chủ đề.",
  "Only collections you can access are searched. Unknown effective dates are marked.": "Chỉ tìm trong các bộ sưu tập bạn có quyền truy cập. Ngày hiệu lực chưa rõ sẽ được đánh dấu.",
  "Effective on": "Có hiệu lực vào ngày",
  "This question is limited to the document you selected.": "Câu hỏi này chỉ tìm trong tài liệu bạn đã chọn.",
  "Your question": "Câu hỏi của bạn",
  "Search terms": "Từ khóa tìm kiếm",
  "e.g. đấu thầu, Article 5, procurement approval": "Ví dụ: đấu thầu, Điều 5, phê duyệt mua sắm",
  "Find supporting passages": "Tìm đoạn trích làm căn cứ",
  "Source {{0}}": "Nguồn {{0}}",
  "Page {{3}} · Effective: {{4}}": "Trang {{3}} · Hiệu lực: {{4}}",
  "Inspect source →": "Kiểm tra nguồn →",
  "Source passage": "Đoạn trích nguồn",
  "Effective on {{3}}": "Có hiệu lực vào ngày {{3}}",
  "{{4}} sources": "{{4}} nguồn",
  "Saved privately to your account": "Được lưu riêng trong tài khoản của bạn",
  "Was this useful?": "Kết quả này có hữu ích không?",
  "Choose feedback…": "Chọn nhận xét…",
  "Useful": "Hữu ích",
  "Wrong source": "Sai nguồn",
  "Outdated information": "Thông tin đã cũ",
  "Incomplete": "Chưa đầy đủ",
  "Does not support the question": "Không làm rõ câu hỏi",
  "Quotations are checked against your uploaded documents. Relevance, completeness and legal applicability still need review.": "Các đoạn trích được đối chiếu với tài liệu bạn tải lên. Vẫn cần xem xét mức độ liên quan, tính đầy đủ và khả năng áp dụng pháp lý.",
  "More evidence needed": "Cần thêm căn cứ",
  "Source quotations": "Trích dẫn nguồn",
  "No supporting evidence": "Chưa có căn cứ phù hợp",
  "Review source context": "Kiểm tra ngữ cảnh của nguồn",
  "No sufficiently relevant source was found in this scope. Try a more specific question, a different collection, or add the missing document.": "Không tìm thấy nguồn đủ liên quan trong phạm vi này. Hãy đặt câu hỏi cụ thể hơn, chọn bộ sưu tập khác hoặc bổ sung tài liệu còn thiếu.",
  "Copy with references": "Sao chép kèm nguồn",
  "Download answer": "Tải câu trả lời xuống",
  "Your questions and source references, available when you need them.": "Câu hỏi và nguồn tham khảo của bạn, sẵn sàng khi cần.",
  "Delete": "Xóa",
  "Your research will appear here": "Nội dung tra cứu sẽ xuất hiện ở đây",
  "Ask a question to save its answer and source references.": "Đặt câu hỏi để lưu câu trả lời và nguồn tham khảo.",
  "Ask a question": "Đặt câu hỏi",
  "Your account": "Tài khoản của bạn",
  "Manage your profile, password and signed-in devices.": "Quản lý hồ sơ, mật khẩu và các thiết bị đã đăng nhập.",
  "Profile": "Hồ sơ",
  "Username: {{2}}": "Tên đăng nhập: {{2}}",
  "Save profile": "Lưu hồ sơ",
  "Change password": "Đổi mật khẩu",
  "Changing your password signs out all devices.": "Đổi mật khẩu sẽ đăng xuất tất cả thiết bị.",
  "Update password": "Cập nhật mật khẩu",
  "Signed-in sessions": "Phiên đăng nhập",
  "Name": "Họ và tên",
  "Email": "Email",
  "Current password": "Mật khẩu hiện tại",
  "Confirm new password": "Nhập lại mật khẩu mới",
  "· Signed in {{1}} · Expires {{2}}": "· Đăng nhập {{1}} · Hết hạn {{2}}",
  "This browser": "Trình duyệt này",
  "Browser session": "Phiên trình duyệt",
  "Sign out of this browser": "Đăng xuất trình duyệt này",
  "Approve access, invite colleagues and manage accounts.": "Duyệt quyền truy cập, mời đồng nghiệp và quản lý tài khoản.",
  "Create invitation": "Tạo lời mời",
  "Each person needs their own account. Collection owners decide which documents to share.": "Mỗi người cần có tài khoản riêng. Chủ bộ sưu tập quyết định tài liệu được chia sẻ.",
  "Person": "Người dùng",
  "Role": "Vai trò",
  "Access": "Quyền truy cập",
  "Manage": "Quản lý",
  "Approve": "Phê duyệt",
  "Enable": "Kích hoạt",
  "Disable": "Vô hiệu hóa",
  "Make member": "Chuyển thành thành viên",
  "Make admin": "Chuyển thành quản trị viên",
  "Choose how this installation processes documents and questions.": "Chọn cách hệ thống xử lý tài liệu và câu hỏi.",
  "Processing mode": "Chế độ xử lý",
  "Local mode searches and quotes documents on this machine. AI-assisted mode sends your question and relevant passages to the provider configured below.": "Chế độ cục bộ tìm kiếm và trích dẫn trên máy này. Chế độ hỗ trợ AI gửi câu hỏi và các đoạn liên quan đến nhà cung cấp được cấu hình bên dưới.",
  "Optional AI provider": "Nhà cung cấp AI (tùy chọn)",
  "Use an Ollama server with an embedding model and a chat model. Changing models may require rebuilding document search.": "Dùng máy chủ Ollama có mô hình embedding và mô hình hội thoại. Đổi mô hình có thể cần tạo lại dữ liệu tìm kiếm.",
  "For another computer, use its LAN address, for example http://192.168.1.50:11434/v1. Ollama must listen on that computer’s network interface.": "Nếu dùng máy khác, nhập địa chỉ LAN của máy đó, ví dụ http://192.168.1.50:11434/v1. Ollama phải được cấu hình nhận kết nối qua mạng.",
  "Advanced options": "Tùy chọn nâng cao",
  "I have approved this destination to process my organization’s questions and document passages.": "Tôi đã phê duyệt địa chỉ này để xử lý câu hỏi và các đoạn tài liệu của tổ chức.",
  "Save and enable": "Lưu và bật",
  "Server operations": "Vận hành máy chủ",
  "Use the Legal Library Server application on the host machine to manage the service, port, HTTPS certificate, backups and recovery.": "Dùng ứng dụng máy chủ Thư viện pháp lý trên máy chủ để quản lý dịch vụ, cổng, chứng chỉ HTTPS, sao lưu và khôi phục.",
  "AI-assisted source selection is enabled.": "Đã bật chọn nguồn với sự hỗ trợ của AI.",
  "Local search is active. Scanned-page OCR is configured separately below.": "Đang dùng tìm kiếm cục bộ. OCR cho trang quét được cấu hình riêng bên dưới.",
  "Switch to local mode": "Chuyển sang chế độ cục bộ",
  "Continue with local mode": "Tiếp tục với chế độ cục bộ",
  "Provider address": "Địa chỉ nhà cung cấp",
  "Chat model": "Mô hình hội thoại",
  "Embedding model": "Mô hình embedding",
  "Provider key (leave empty to keep at the same address)": "Khóa API (để trống để giữ khóa tại cùng địa chỉ)",
  "Provider key (if required)": "Khóa API (nếu cần)",
  "Response timeout (seconds)": "Thời gian chờ phản hồi (giây)",
  "Maximum response tokens": "Số token phản hồi tối đa",
  "Reasoning": "Mức suy luận",
  "None": "Không",
  "Low": "Thấp",
  "Medium": "Trung bình",
  "Test connection": "Kiểm tra kết nối",
  "Check server status": "Kiểm tra máy chủ",
  "Allow this provider on my local network": "Cho phép nhà cung cấp này trên mạng nội bộ",
  "Reading scanned PDFs (OCR)": "Đọc PDF dạng quét (OCR)",
  "Text PDFs and Word files are extracted on this server. These settings apply only to pages that need image recognition, independently of AI-assisted answers.": "PDF có văn bản và tệp Word được trích xuất trên máy chủ này. Các cài đặt này chỉ áp dụng cho trang cần nhận dạng hình ảnh, độc lập với tính năng trả lời có AI hỗ trợ.",
  "I approve sending scanned page images to this provider, including automatic fallback when selected.": "Tôi đồng ý gửi ảnh trang quét đến nhà cung cấp này, kể cả khi tự động dùng làm phương án dự phòng đã chọn.",
  "Save OCR settings": "Lưu cài đặt OCR",
  "Test OCR sends only a generated test image. Saving affects new processing and retries; existing transcriptions stay unchanged. Retry failed documents after fixing settings.": "Kiểm tra OCR chỉ gửi ảnh thử do hệ thống tạo. Cài đặt mới áp dụng khi xử lý mới hoặc thử lại, không thay đổi văn bản đã trích xuất. Hãy thử lại tài liệu bị lỗi sau khi sửa cài đặt.",
  "OCR method": "Phương pháp OCR",
  "Tesseract on this server": "Tesseract trên máy chủ này",
  "Vision model (no Tesseract required)": "Mô hình thị giác (không cần Tesseract)",
  "Try Tesseract, then use vision if it fails": "Thử Tesseract, dùng mô hình thị giác nếu thất bại",
  "Vision provider address": "Địa chỉ nhà cung cấp mô hình thị giác",
  "Vision model": "Mô hình thị giác",
  "Vision key (leave empty to keep at the same address)": "Khóa API thị giác (để trống để giữ khóa tại cùng địa chỉ)",
  "Vision API key (optional for Ollama)": "Khóa API thị giác (không bắt buộc với Ollama)",
  "Time per scanned page (seconds)": "Thời gian cho mỗi trang quét (giây)",
  "Maximum page output tokens": "Số token đầu ra tối đa mỗi trang",
  "Maximum vision pages per document": "Số trang dùng mô hình thị giác tối đa mỗi tài liệu",
  "Vision OCR can omit or invent text. Verify numbers, dates and tables against the original. Provider charges may apply to page images.": "OCR thị giác có thể bỏ sót hoặc tạo thêm nội dung. Hãy đối chiếu số liệu, ngày tháng và bảng với bản gốc. Nhà cung cấp có thể tính phí xử lý ảnh trang.",
  "Test OCR": "Kiểm tra OCR",
  "Enter a vision provider address and model, and approve sending scanned page images.": "Nhập địa chỉ và mô hình thị giác, đồng thời đồng ý gửi ảnh trang quét.",
  "A quick guide to using your library.": "Hướng dẫn nhanh để sử dụng thư viện.",
  "Getting started": "Bắt đầu sử dụng",
  "Create a collection and add colleagues in Sharing.": "Tạo bộ sưu tập và thêm đồng nghiệp trong mục Chia sẻ.",
  "Upload PDF or DOCX files. Optional dates and tags help people understand them.": "Tải tệp PDF hoặc DOCX lên. Ngày áp dụng và nhãn giúp người dùng hiểu rõ tài liệu hơn.",
  "Wait for": "Chờ trạng thái",
  ". If a file needs attention, inspect the reason and retry.": ". Nếu tệp cần kiểm tra, xem nguyên nhân và thử lại.",
  "Ask a specific question and select the relevant collection.": "Đặt câu hỏi cụ thể và chọn bộ sưu tập liên quan.",
  "Open each source, check its version and surrounding text, then copy the answer with references.": "Mở từng nguồn, kiểm tra phiên bản và nội dung xung quanh, rồi sao chép câu trả lời kèm nguồn.",
  "Finding a document": "Tìm tài liệu",
  "In Documents, choose a collection, enter part of its title or document number and choose Apply filters. Vietnamese titles also match without accents. Filters search the whole accessible library. Show lets you find ready, processing, needs-attention or archived documents. Clear filters returns to active documents.": "Trong mục Tài liệu, chọn bộ sưu tập, nhập một phần tiêu đề hoặc số hiệu rồi chọn Áp dụng bộ lọc. Tiêu đề tiếng Việt có thể tìm không dấu. Bộ lọc tìm trong toàn bộ thư viện bạn có quyền truy cập. Mục Hiển thị cho phép tìm tài liệu sẵn sàng, đang xử lý, cần kiểm tra hoặc đã lưu trữ. Xóa bộ lọc để trở về tài liệu đang sử dụng.",
  "Contributing and uploading": "Đóng góp và tải tài liệu lên",
  "Viewers can read sources. Contributors can upload and edit details. Collection managers can also share access, retry processing, archive, restore and replace versions. Upload destinations only include collections you can contribute to.": "Người xem được đọc nguồn. Người đóng góp được tải lên và sửa thông tin. Người quản lý bộ sưu tập còn được chia sẻ quyền, thử xử lý lại, lưu trữ, khôi phục và thay phiên bản. Danh sách nơi tải lên chỉ gồm bộ sưu tập bạn được phép đóng góp.",
  "You can browse this library while a batch uploads. Keep the browser open until all files have been sent; processing then continues on the server. Signing out cancels remaining transfers and clears selected files from this browser. A file already accepted by the server can still finish processing.": "Bạn có thể xem thư viện khi đang tải một lô tài liệu. Giữ trình duyệt mở đến khi gửi xong tất cả tệp; máy chủ sẽ tiếp tục xử lý. Đăng xuất sẽ hủy phần tải lên còn lại và xóa lựa chọn tệp khỏi trình duyệt. Tệp đã được máy chủ tiếp nhận vẫn có thể được xử lý xong.",
  "Understanding the answer": "Hiểu câu trả lời",
  "Answers contain exact source passages. With AI enabled, the model selects passages; the server verifies the quotations before showing them. A source can be accurately quoted and still be incomplete, outdated or inapplicable to your situation.": "Câu trả lời chứa các đoạn trích nguyên văn. Khi bật AI, mô hình chọn đoạn trích và máy chủ kiểm tra trước khi hiển thị. Nguồn được trích đúng vẫn có thể chưa đầy đủ, đã cũ hoặc không áp dụng cho tình huống của bạn.",
  "The effective date filter uses the dates recorded on your documents. Unknown dates are labelled. It does not automatically discover amendments or certify current law.": "Bộ lọc hiệu lực dùng ngày đã ghi trên tài liệu. Ngày chưa rõ được đánh dấu. Hệ thống không tự phát hiện văn bản sửa đổi hoặc xác nhận pháp luật hiện hành.",
  "Who can see my work?": "Ai có thể xem nội dung của tôi?",
  "Collection owners control document access. Saved answers are private to your account and are hidden if you lose access to their source collections. Server administrators control accounts and processing settings; the host operator can access server backups.": "Chủ bộ sưu tập kiểm soát quyền xem tài liệu. Câu trả lời được lưu riêng và sẽ ẩn nếu bạn mất quyền truy cập bộ sưu tập nguồn. Quản trị viên quản lý tài khoản và cài đặt xử lý; người vận hành máy chủ có thể truy cập bản sao lưu.",
  "Scanned documents": "Tài liệu dạng quét",
  "Scans need Tesseract with Vietnamese language data or an administrator-configured vision OCR provider. Vision OCR sends scanned page images to that provider and may misread or invent text. Unreadable or incomplete pages are reported instead of quietly skipped. Ask your administrator to configure OCR, then retry and compare the result with the original file.": "Tài liệu quét cần Tesseract có dữ liệu tiếng Việt hoặc nhà cung cấp OCR thị giác do quản trị viên cấu hình. OCR thị giác gửi ảnh trang đến nhà cung cấp đó và có thể đọc sai hoặc tạo thêm nội dung. Trang không đọc được hoặc chưa đầy đủ sẽ được báo lỗi thay vì bỏ qua. Nhờ quản trị viên cấu hình OCR, sau đó thử lại và đối chiếu với tệp gốc.",
  "Need access or a password reset?": "Cần quyền truy cập hoặc đặt lại mật khẩu?",
  "Contact your organization’s administrator. They can approve an account, issue an invitation, or give you a recovery code. A password reset signs out existing sessions.": "Liên hệ quản trị viên của tổ chức để được duyệt tài khoản, cấp lời mời hoặc mã khôi phục. Đặt lại mật khẩu sẽ đăng xuất các phiên hiện có.",
  "Passwords do not match.": "Mật khẩu nhập lại không khớp.",
  "Password reset. Sign in with your new password.": "Đã đặt lại mật khẩu. Hãy đăng nhập bằng mật khẩu mới.",
  "Access requested": "Đã gửi yêu cầu truy cập",
  "Your account is waiting for administrator approval. You can sign in once it is approved.": "Tài khoản đang chờ quản trị viên phê duyệt. Bạn có thể đăng nhập sau khi được duyệt.",
  "Collection created.": "Đã tạo bộ sưu tập.",
  "Finding relevant source passages…": "Đang tìm đoạn trích liên quan…",
  "{{0}} passages · {{1}} search": "{{0}} đoạn trích · tìm kiếm {{1}}",
  "No results in this scope": "Không có kết quả trong phạm vi này",
  "Try a document number, a distinctive phrase, or a broader collection.": "Thử số hiệu văn bản, cụm từ đặc trưng hoặc bộ sưu tập rộng hơn.",
  "Profile saved.": "Đã lưu hồ sơ.",
  "Password changed. Please sign in again.": "Đã đổi mật khẩu. Vui lòng đăng nhập lại.",
  "Sharing updated.": "Đã cập nhật chia sẻ.",
  "OCR settings saved. Retry documents that need attention.": "Đã lưu cài đặt OCR. Hãy thử lại các tài liệu cần kiểm tra.",
  "AI provider enabled. New uploads will use this configuration.": "Đã bật nhà cung cấp AI. Tài liệu tải lên mới sẽ dùng cấu hình này.",
  "Choose a file of at most 25 MB.": "Chọn tệp không quá 25 MB.",
  "New version uploaded and queued.": "Đã tải phiên bản mới lên và đưa vào hàng chờ.",
  "Document details updated.": "Đã cập nhật thông tin tài liệu.",
  "Another batch is uploading. Wait for it to finish.": "Một lô tài liệu khác đang tải lên. Hãy chờ hoàn tất.",
  "Choose a collection.": "Hãy chọn bộ sưu tập.",
  "Choose at least one PDF or DOCX file.": "Chọn ít nhất một tệp PDF hoặc DOCX.",
  "The end date must be after the effective date.": "Ngày kết thúc phải sau ngày bắt đầu có hiệu lực.",
  "Every file needs a title.": "Mỗi tệp cần có tiêu đề.",
  "exceeds 25 MB.": "vượt quá 25 MB.",
  "Uploading…": "Đang tải lên…",
  "Uploaded. Preparing document…": "Đã tải lên. Đang chuẩn bị tài liệu…",
  "{{0}} uploaded{{1}}": "Đã tải lên {{0}} tài liệu{{1}}",
  "Processing continues on the server. You can leave this page.": "Máy chủ vẫn tiếp tục xử lý. Bạn có thể rời trang này.",
  "View processing progress →": "Xem tiến độ xử lý →",
  "Correct any reported problems and choose Upload documents again. Successful files will not be uploaded twice.": "Khắc phục lỗi được báo và chọn Tải tài liệu lên lần nữa. Tệp đã tải thành công sẽ không bị tải trùng.",
  "{{0}} documents uploaded{{1}}.": "Đã tải lên {{0}} tài liệu{{1}}.",
  "Choose more files to upload": "Chọn thêm tệp để tải lên",
  "Wait for the current upload batch to finish.": "Hãy chờ lô tài liệu hiện tại tải lên xong.",
  "Choose up to 50 documents at a time.": "Mỗi lần chọn tối đa 50 tài liệu.",
  "Skipped unsupported files and Office temporary files.": "Đã bỏ qua tệp không hỗ trợ và tệp tạm của Office.",
  "Feedback saved. Thank you.": "Đã lưu nhận xét. Cảm ơn bạn.",
  "Collection sharing": "Chia sẻ bộ sưu tập",
  "Only people listed here can use this collection.": "Chỉ người có trong danh sách này được sử dụng bộ sưu tập.",
  "Save access": "Lưu quyền truy cập",
  "Remove": "Gỡ bỏ",
  "Can read and ask": "Được đọc và hỏi đáp",
  "Can read and upload": "Được đọc và tải lên",
  "Can manage documents and sharing": "Được quản lý tài liệu và chia sẻ",
  "Save details": "Lưu thông tin",
  "Source and versions": "Nguồn và phiên bản",
  "Original: {{14}}": "Tệp gốc: {{14}}",
  "Archiving removes a document from normal search and preserves its source. Only authorized collection managers can change its lifecycle.": "Lưu trữ sẽ loại tài liệu khỏi tìm kiếm thông thường nhưng vẫn giữ nguồn. Chỉ người quản lý bộ sưu tập có quyền mới được thay đổi trạng thái vòng đời.",
  "Ask this document": "Hỏi về tài liệu này",
  "Original file": "Tệp gốc",
  "Retry processing": "Xử lý lại",
  "Title": "Tiêu đề",
  "Description": "Mô tả",
  "Issued by": "Cơ quan ban hành",
  "Upload new version": "Tải phiên bản mới lên",
  "Version {{0}} · {{1}} · {{2}}": "Phiên bản {{0}} · {{1}} · {{2}}",
  "Download this version": "Tải phiên bản này xuống",
  "Restore document": "Khôi phục tài liệu",
  "Archive document": "Lưu trữ tài liệu",
  "[{{0}}] {{1}} — {{2}}; version {{3}}; effective {{4}}; page {{5}}": "[{{0}}] {{1}} — {{2}}; phiên bản {{3}}; hiệu lực {{4}}; trang {{5}}",
  "New collection": "Bộ sưu tập mới",
  "Only you can access a new collection until you add people in Sharing.": "Chỉ bạn có quyền truy cập bộ sưu tập mới cho đến khi thêm người trong mục Chia sẻ.",
  "Collection name": "Tên bộ sưu tập",
  "Description (optional)": "Mô tả (không bắt buộc)",
  "Access removed.": "Đã gỡ quyền truy cập.",
  "Queued for processing.": "Đã đưa vào hàng chờ xử lý.",
  "Archive document?": "Lưu trữ tài liệu?",
  "This removes the document from normal search. Its source file will be kept.": "Tài liệu sẽ không xuất hiện trong tìm kiếm thông thường. Tệp nguồn vẫn được giữ lại.",
  "Archive": "Lưu trữ",
  "Document archived.": "Đã lưu trữ tài liệu.",
  "Document restored.": "Đã khôi phục tài liệu.",
  "Upload a new version": "Tải lên phiên bản mới",
  "This keeps previous source files and citations, and replaces the version used for new searches.": "Giữ các tệp nguồn và trích dẫn trước đây, đồng thời thay phiên bản dùng cho lần tìm kiếm mới.",
  "PDF or DOCX": "PDF hoặc DOCX",
  "Upload version": "Tải phiên bản lên",
  "{{0}} · Page {{1}}": "{{0}} · Trang {{1}}",
  "Version {{2}}": "Phiên bản {{2}}",
  "Extracted source text": "Văn bản nguồn đã trích xuất",
  "Surrounding page text": "Nội dung xung quanh trên trang",
  "Download original": "Tải bản gốc xuống",
  "Inspect this page and compare with the original file.": "Kiểm tra trang này và đối chiếu với tệp gốc.",
  "No extracted text available for this page.": "Trang này chưa có văn bản được trích xuất.",
  "Not available": "Không có",
  "Answer and references copied.": "Đã sao chép câu trả lời và nguồn tham khảo.",
  "Copy answer": "Sao chép câu trả lời",
  "Select the text and copy it.": "Chọn văn bản và sao chép.",
  "Saved answer deleted.": "Đã xóa câu trả lời đã lưu.",
  "Invitation created": "Đã tạo lời mời",
  "Share this one-time link privately with a colleague. It expires {{0}}.": "Gửi riêng liên kết dùng một lần này cho đồng nghiệp. Liên kết hết hạn {{0}}.",
  "The recipient can create an approved member account. Collections still need to be shared separately.": "Người nhận có thể tạo tài khoản thành viên đã được duyệt. Quyền vào bộ sưu tập vẫn cần được chia sẻ riêng.",
  "Password recovery code": "Mã khôi phục mật khẩu",
  "Give this code privately to the account owner. It expires in one hour and can be used once.": "Gửi riêng mã này cho chủ tài khoản. Mã hết hạn sau một giờ và chỉ dùng được một lần.",
  "They can choose “Forgot password?” on the sign-in page.": "Người dùng chọn “Quên mật khẩu?” trên trang đăng nhập.",
  "Account updated.": "Đã cập nhật tài khoản.",
  "Checking OCR…": "Đang kiểm tra OCR…",
  "Local processing enabled.": "Đã bật xử lý cục bộ.",
  "The server is responding.": "Máy chủ đang hoạt động.",
  "Your session ended. Please sign in again.": "Phiên đăng nhập đã kết thúc. Vui lòng đăng nhập lại.",
  "Search all matching documents…": "Tìm trong tất cả tài liệu phù hợp…",
  "e.g. Your organization": "Ví dụ: Tổ chức của bạn",
  "procurement, internal": "mua sắm, nội bộ",
  "e.g. Procurement policies": "Ví dụ: Quy định mua sắm",
  "need attention": "cần kiểm tra",
  "documents visible to your account.": "tài liệu mà tài khoản của bạn được xem.",
  "Skip to content": "Chuyển đến nội dung",
  "Opening your library…": "Đang mở thư viện…",
  "Please try again.": "Vui lòng thử lại.",
  "Cannot reach the server. Check your connection and try again.": "Không thể kết nối với máy chủ. Kiểm tra kết nối và thử lại.",
  "Change language?": "Đổi ngôn ngữ?",
  "Changing language reloads this page. Unsaved entries and selected files will be cleared. Continue?": "Đổi ngôn ngữ sẽ tải lại trang. Nội dung chưa lưu và các tệp đang chọn sẽ bị xóa khỏi biểu mẫu. Bạn có muốn tiếp tục không?",
  "Language could not be saved. Allow this site to store preferences and try again.": "Không thể lưu ngôn ngữ. Hãy cho phép trang này lưu tùy chọn rồi thử lại.",
  "Invalid username or password.": "Tên đăng nhập hoặc mật khẩu không đúng.",
  "Administrator access required.": "Cần quyền quản trị viên.",
  "Sign in required.": "Vui lòng đăng nhập.",
  "Authentication required.": "Vui lòng đăng nhập.",
  "Password must be between 12 and 256 characters.": "Mật khẩu phải có từ 12 đến 256 ký tự.",
  "Current password is incorrect.": "Mật khẩu hiện tại không đúng.",
  "Provider is reachable and usable.": "Đã kết nối và có thể sử dụng nhà cung cấp.",
  "Tesseract was not found. Install it on the library server or choose vision OCR below.": "Không tìm thấy Tesseract. Hãy cài trên máy chủ thư viện hoặc chọn OCR bằng mô hình thị giác bên dưới.",
  "Tesseract is ready for Vietnamese and English.": "Tesseract đã sẵn sàng cho tiếng Việt và tiếng Anh.",
  "Tesseract needs both Vietnamese (vie) and English (eng) language data, or choose vision OCR.": "Tesseract cần dữ liệu tiếng Việt (vie) và tiếng Anh (eng). Bạn cũng có thể chọn OCR bằng mô hình thị giác.",
  "Tesseract could not start. Check its installation or choose vision OCR.": "Không thể khởi động Tesseract. Kiểm tra cài đặt hoặc chọn OCR bằng mô hình thị giác.",
  "The model read the test image. Review real Vietnamese scans before relying on its transcriptions.": "Mô hình đã đọc được ảnh thử. Hãy kiểm tra trên tài liệu quét tiếng Việt thực tế trước khi sử dụng kết quả.",
  "The provider replied, but did not read the test image correctly. Choose a vision-capable model and check its settings.": "Nhà cung cấp đã phản hồi nhưng đọc ảnh thử không đúng. Chọn mô hình hỗ trợ hình ảnh và kiểm tra cài đặt.",
  "Approve sending scanned page images to the configured OCR provider.": "Hãy đồng ý gửi ảnh trang quét đến nhà cung cấp OCR đã cấu hình.",
  "Word page layout is not preserved. These locations refer to extracted text.": "Bố cục trang Word không được giữ nguyên. Các vị trí này chỉ đến văn bản đã trích xuất.",
  "For OCR sources, check recognition against the original file.": "Với nguồn OCR, hãy đối chiếu văn bản nhận dạng với tệp gốc.",
  "Scanned text was recognized automatically. Verify figures, dates and tables against the original.": "Văn bản quét được nhận dạng tự động. Hãy đối chiếu số liệu, ngày tháng và bảng với bản gốc.",
  "Active": "Đang hoạt động",
  "Pending approval": "Chờ phê duyệt",
  "Disabled": "Đã vô hiệu hóa",
  "Owner": "Chủ sở hữu",
  "Viewer": "Người xem",
  "Contributor": "Người đóng góp",
  "Manager": "Người quản lý",
  "Hybrid": "Kết hợp",
  "Keyword": "Từ khóa",
  "Semantic": "Ngữ nghĩa",
  "Unknown": "Chưa rõ",
  "{{0}}\n\n{{1}}\n\nSources:\n{{2}}\n\nEffective-on filter: {{3}}\nSource quotations; verify applicability and completeness.": "{{0}}\n\n{{1}}\n\nNguồn:\n{{2}}\n\nBộ lọc ngày hiệu lực: {{3}}\nTrích dẫn nguồn; cần kiểm tra khả năng áp dụng và tính đầy đủ.",
  "Use a password with 12–256 characters.": "Dùng mật khẩu có từ 12 đến 256 ký tự.",
  "Username must have 3–80 letters, numbers, or . _ @ + - characters.": "Tên đăng nhập phải có 3–80 chữ cái, chữ số hoặc các ký tự . _ @ + -.",
  "Enter a valid name and email address.": "Nhập họ tên và địa chỉ email hợp lệ.",
  "The setup code is invalid or this server already has an administrator.": "Mã thiết lập không hợp lệ hoặc máy chủ đã có quản trị viên.",
  "The server owner needs to finish setup first.": "Chủ máy chủ cần hoàn tất thiết lập trước.",
  "Invitation is invalid, expired, or belongs to another email address.": "Lời mời không hợp lệ, đã hết hạn hoặc thuộc về địa chỉ email khác.",
  "That username is already registered.": "Tên đăng nhập này đã được đăng ký.",
  "Enter your username and password.": "Nhập tên đăng nhập và mật khẩu.",
  "Too many attempts. Please try again in 15 minutes.": "Bạn đã thử quá nhiều lần. Vui lòng thử lại sau 15 phút.",
  "Username or password is incorrect.": "Tên đăng nhập hoặc mật khẩu không đúng.",
  "Your account is awaiting approval or has been disabled. Contact your administrator.": "Tài khoản đang chờ phê duyệt hoặc đã bị vô hiệu hóa. Hãy liên hệ quản trị viên.",
  "Please sign in.": "Vui lòng đăng nhập.",
  "Recovery code is invalid or expired.": "Mã khôi phục không hợp lệ hoặc đã hết hạn.",
  "Account not found.": "Không tìm thấy tài khoản.",
  "Invalid account status or role.": "Trạng thái hoặc vai trò tài khoản không hợp lệ.",
  "Keep at least one active administrator.": "Phải giữ ít nhất một quản trị viên đang hoạt động."
});
